### ISSUE TITLE
python manage.py migrate 的时候出现错误信息

### ISSUE THREAD

**Issue by hannoch** [GreaterWMS/GreaterWMS#13]
ERRORS:
asn.AsnListModel: (fields.E180) SQLite does not support JSONFields.
dn.DnListModel: (fields.E180) SQLite does not support JSONFields.

解决：
SQLite3报错处理
我在Windows下开发测试时，当migrate生成表的时候遇到了如下报错，这主要是因为SQLite不支持JSONFields导致的
SQLite does not support JSONFields
解决方法为：
1、先去sqlite官网下载对应的DLL软件包https://www.sqlite.org/download.html，
2、然后替换掉当前使用的sqlite3.dll文件。
例如我的windows为64位版本，所以下载了sqlite-dll-win64-x64-3340100.zip这个软件包，本地python的安装路径为C:\python38，直接将C:\python38\DLLs\sqlite3.dll（使用虚拟环境也是在本地python38的安装路径目录下）用下载的软件包里的sqlite3.dll文件替换，然后再次运行migrate顺利创建了数据库表

**Comment by Singosgu** [comment]
非常感谢支持

**Comment by skyydq** [comment]
提示这个错误 
ImportError: cannot import name 'get_random_secret_key' from 'django.core.management.utils' (C:\python\lib\site-packages\django\core\management\utils.py)

**Comment by Singosgu** [comment]
你库没装好
