### ISSUE TITLE
提示这个错误

### ISSUE THREAD

**Issue by Singosgu** [GreaterWMS/GreaterWMS#20]
提示这个错误 
ImportError: cannot import name 'get_random_secret_key' from 'django.core.management.utils' (C:\python\lib\site-packages\django\core\management\utils.py)

_Originally posted by @skyydq in https://github.com/Singosgu/GreaterWMS/issues/13#issuecomment-819178301_

**Comment by Singosgu** [comment]
库没装好

**Comment by skyydq** [comment]
这个哪个库， 库名是什么， 我单独的 装下

**Comment by Singosgu** [comment]
requirements.txt里面的库全部要装，还要看你python版本，不能太低，否则就要自己手动装
https://space.bilibili.com/407321291/channel/detail?cid=152043
也可以去B站看安装教程

**Comment by skyydq** [comment]
搞定了，进去怎么是英文的，怎么弄成中文

**Comment by Singosgu** [comment]
右上角有个字体更改

**Comment by skyydq** [comment]
搞定了，虽然功能少，但界面风格很舒服

**Comment by skyydq** [comment]
只有框架，要做成业务框架 还有很长的路啊

**Comment by Singosgu** [comment]
功能少？你仔细研究下，今天会放交互讲解

**Comment by skyydq** [comment]
我的的意思是，我下载的源码运行，虽然有好几个菜单模块，但具体框架比较简单，比如没有主从表界面 ，没有弹出框选择多条数据，类似这样的前端 组件
