### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by huyngh** [GreaterWMS/GreaterWMS#218]
Now I want to develop more to Container manager System from this source code it ok?

**Comment by Singosgu** [comment]
ok , no problem

**Comment by huyngh** [comment]
Thank so much

Vào Th 5, 7 thg 7, 2022 vào lúc 13:47 GreaterWMS ***@***.***>
đã viết:

**Comment by Singosgu** [comment]
Don't worry about Commercial License. You will get Free Commercial License while you download the source code .

**Comment by huyngh** [comment]
Thank so much

**Comment by huyngh** [comment]
I saw the database in Python no a relationship in it? so how tables connect with each other?

**Comment by Singosgu** [comment]
Django ORM, You can change to other database

**Comment by huyngh** [comment]
Thank you
