### ISSUE TITLE
try to use it in ubuntu 20.04 however No module named 'asgihandler'

### ISSUE THREAD

**Issue by sdw2020** [GreaterWMS/GreaterWMS#224]
hi,

we try to run it in ubuntu 20.04. However, it shows that "No module named 'asgihandler'" for from asgihandler.core import ASGIHandler, which is line 14 in /greaterwms/asgi.py. is it missing somthing? 
asgihandler==0.3.3 is also could not be found in everywhere.

**Describe the bug**

**Steps to Reproduce**

**Expected behavior**

**Deployment Method**
- [x] Docker
- [x] Bare Metal

**Version Information**

**Comment by Singosgu** [comment]
pip3 install asgihandler==0.3.3 -i https://pypi.python.org/simple/
