### ISSUE TITLE
我用docker部署完后，无法注册

### ISSUE THREAD

**Issue by wangweitung** [GreaterWMS/GreaterWMS#226]
我用的这个方法部署的docker，网页也可以打开，但是无法注册。

部署步骤：

```
cd GreaterWMS/
docker-compose up -d
docker-compose restart
```

![image](https://user-images.githubusercontent.com/8080125/187209014-3bfa7f7f-2171-45a4-9522-dd9376666aaa.png)

**Comment by Singosgu** [comment]
supervisor里面，把-b 0.0.0.0去掉就可以了

**Comment by wangweitung** [comment]
> supervisor里面，把-b 0.0.0.0去掉就可以了
如下图，删除了GreaterWMS文件夹下的`supervisor`文件里面的`-b 0.0.0.0` 。
![20220831125850](https://user-images.githubusercontent.com/8080125/187596116-00ae7fd5-150d-449e-80ca-0ba9c137a327.png)
然后`docker-compose up -d`
结果还是一样，无法注册：
![20220831125728](https://user-images.githubusercontent.com/8080125/187596257-7971b0b0-fef2-4fb2-8180-faa35e1a5251.png)

**Comment by wangweitung** [comment]
并且：8008端口的页面也打不开了。

**Comment by wangweitung** [comment]
用ubuntu server很容易复现的。
1、git clone https://github.com/GreaterWMS/GreaterWMS.git。
2、cd GreaterWMS/。
3、删除supervisor文件里面的-b 0.0.0.0 。
4、docker-compose up -d。
5、docker-compose restart。
6、打开ip:8080，注册失败。
7、打开ip:8008，打开失败。

**Comment by Singosgu** [comment]
你等下，好像有人动过docker代码了

**Comment by cow11023** [comment]
可能是您的baseurl.js 没修改，可以参照我们的Docker部署文档https://www.56yhz.com/zh-hans/docs/39/14/

**Comment by wangweitung** [comment]
> 可能是您的baseurl.js 没修改，可以参照我们的Docker部署文档https://www.56yhz.com/zh-hans/docs/39/14/

需要改哪里呢？

**Comment by wangweitung** [comment]
是第6步里，把127.0.0.1改成啥？docker的虚拟地址172.18.0.2？


6.开始部署
//拉取代码
git clone https://gitee.com/Singosgu/GreaterWMS.git
//运行项目前需要修改baseurl.js的内容
vim templates/public/statics/baseurl.js //将127.0.0.1修改为服务器的IP地址
//运行项目前需要修改nginx.conf的内容
vim nginx.conf //将127.0.0.1修改为本机IP地址，如果部署到服务器，修改为服务器IP地址

**Comment by cow11023** [comment]
不是，baseurl.js要改成你部署机器的局域网IP地址

**Comment by wangweitung** [comment]
> 

稍等，我重新部署下试试

**Comment by cow11023** [comment]
我更新了一下docker相关的代码，您更新一下

**Comment by wangweitung** [comment]
> 我更新了一下docker相关的代码，您更新一下

好，我重新拉取下代码。

**Comment by Singosgu** [comment]
已经可以了

**Comment by wangweitung** [comment]
> 已经可以了

的确可以了。
但仍有一个问题：部署OK后，首次打开页面，提示注册管理员。更换新web/手机端登陆后，仍然提示注册管理员。不应该只有一个管理员账号吗？

另外，如下图的登陆界面，也有提示注册为管理员，就意味着所有人都可以随意注册管理员账号。这样不利于数据的管理。
![image](https://user-images.githubusercontent.com/8080125/187835747-72b032af-104d-4676-b5a2-66b4fccbb7dd.png)

**Comment by Singosgu** [comment]
一个管理员对应的是一个仓库的数据，不同管理员，后台数据不互通

**Comment by wangweitung** [comment]
> 一个管理员对应的是一个仓库的数据，不同管理员，后台数据不互通

通常情况下，第一个管理员创建后，应该禁止其他人再注册成为管理员。

**Comment by Singosgu** [comment]
可以登入，管理员的数据是分离的，而且你是注册仓库管理员，不是超级用户管理员
