### ISSUE TITLE
[BUG] Spanish language shows Russian

### ISSUE THREAD

**Issue by ejgarcian** [GreaterWMS/GreaterWMS#240]
**Describe the bug**

When you set spanish language its failure

**Steps to Reproduce**

1. Go to '... language menu'
2. Click on '.... Espanol'

**Expected behavior**

You can see the GreatWMS in Spanish language as the same behavior when select another

**Deployment Method**
- [ ] Docker
- [ ] Bare Metal

**Version Information**

**Comment by Singosgu** [comment]
In /templates/src/layouts/MainLayout.vue 

line 644 

we have fix it
