### ISSUE TITLE
docker-compose start error

### ISSUE THREAD

**Issue by kasila** [GreaterWMS/GreaterWMS#247]
docker-compose up -d

greaterwms-mysql      "docker-entrypoint.s…"   greaterwms-mysql    running   
greaterwms_backend   "/bin/bash -c 'bash …"   backend                    restarting
greaterwms_front        "docker-entrypoint.s…"   front                         restarting

docker-compose logs front
greaterwms_front  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
greaterwms_front  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
greaterwms_front  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
greaterwms_front  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
greaterwms_front  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
greaterwms_front  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
greaterwms_front  | exec /usr/local/bin/docker-entrypoint.sh: exec format error

docker-compose logs backend
greaterwms_backend  | exec /bin/bash: exec format error
greaterwms_backend  | exec /bin/bash: exec format error
greaterwms_backend  | exec /bin/bash: exec format error
greaterwms_backend  | exec /bin/bash: exec format error
greaterwms_backend  | exec /bin/bash: exec format error
greaterwms_backend  | exec /bin/bash: exec format error
greaterwms_backend  | exec /bin/bash: exec format error

remove docker image, edit docker-compose.yml, add  platform: linux/amd64.  re running docker-compose up -d

Error response from daemon: image with reference greaterwms/greaterwms_front:latest was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8

docker image is an arm platform.

**Comment by cow11023** [comment]
镜像我重新传了一次，您再重新拉取一次代码 docker-comose.yml文件我也修改了一次

**Comment by Singosgu** [comment]
we have fix docker bug . you can re-download it
