### ISSUE TITLE
[BUG] Cannot register Admin Network Exception

### ISSUE THREAD

**Issue by pupank** [GreaterWMS/GreaterWMS#251]
Cannot register admin
it says Network exception
![execption](https://user-images.githubusercontent.com/51271594/203758874-b3939c94-1ed5-486c-a245-0d385d38d1f6.jpg)

**Comment by Singosgu** [comment]
change your baseurl and quasar build

**Comment by pupank** [comment]
thank you for the reply
im sorry but its my first time run this system.
how should i change quasar and base url?
for baseurl i already changed it to my ip

**Comment by Singosgu** [comment]
GreaterWMS/templates/public/statics/baseurl.txt

**Comment by asoral** [comment]
I changed the base url too but still the same error

**Comment by abdellaui** [comment]
same here, changing baseurl doesnt help, see: https://github.com/abdellaui/GreaterWMS/blob/master/templates/public/statics/baseurl.txt

**Comment by Singosgu** [comment]
http://greaterwms.onrender.com:80/

**Comment by dotruong1994** [comment]
I got the same problem, anyone has a solution yet?

**Comment by Singosgu** [comment]
@abdellaui 
you lost one '/'

**Comment by abdellaui** [comment]
@Singosgu look at https://github.com/abdellaui/GreaterWMS/commits/master 

I tried all possible combinations, but it seems to not work... are you sure that the missing / was the reason? i tried everything. with custom domain and with onrender.com domain

**Comment by Singosgu** [comment]
@abdellaui 
It seems you don't know how to exploy

http://greaterwms.onrender.com/

or 

https://greaterwms.onrender.com/

is ok.

**Comment by abdellaui** [comment]
@Singosgu thx for your help. i tried this, but seems to not work :/

**Comment by Singosgu** [comment]
you must use nginx

**Comment by abdellaui** [comment]
@Singosgu thank you a lot for helping me out. Do you know if render.com supports nginx? I updated my nginx.conf lilke this: 

https://github.com/abdellaui/GreaterWMS/blob/master/nginx.conf

**Comment by Singosgu** [comment]
line 52		root /;

it must be GreaterWMS base folder

line 64	       proxy_pass http://wms.davinci-consulting.net/;
it is 	       proxy_pass http://GreaterWMS/;

I don't find your ssl key and pem

So your nginx will not run

**Comment by abdellaui** [comment]
@Singosgu i removed all ssl/tls related code, so it should work without the keys, but it doesnt work :/

**Comment by Singosgu** [comment]
you should know how to use nginx and linux

**Comment by bugprogram-git** [comment]
use docker deploy and is not work

**Comment by bugprogram-git** [comment]
when i register to admin it execption network error

**Comment by bugprogram-git** [comment]
this docker image have some problem 
this is the docker-compose logs
2023-03-22 17:24:49,837 INFO RPC interface 'supervisor' initialized
greaterwms_backend  | 2023-03-22 17:24:49,837 CRIT Server 'unix_http_server' running without any HTTP authentication checking
greaterwms_backend  | 2023-03-22 17:24:49,837 INFO supervisord started with pid 13
greaterwms_backend  | 2023-03-22 17:24:50,838 INFO spawnerr: can't find command 'daphne'
greaterwms_backend  | 2023-03-22 17:24:51,840 INFO spawnerr: can't find command 'daphne'
greaterwms_backend  | 2023-03-22 17:24:53,842 INFO spawnerr: can't find command 'daphne'
greaterwms_backend  | 2023-03-22 17:24:56,845 INFO spawnerr: can't find command 'daphne'
greaterwms_backend  | 2023-03-22 17:24:56,846 INFO gave up: greaterwms entered FATAL state, too many start retries too quickly

**Comment by Singosgu** [comment]
ok，we will fix it

**Comment by bugprogram-git** [comment]
I would like to know what the function of this baseurl.txt is. If my project is to be deployed on the public network, should this be changed to the ip and port of the public network?

**Comment by Singosgu** [comment]
no you can use domin

**Comment by nug1e** [comment]
> ok，we will fix it

any update about this issue?

**Comment by Singosgu** [comment]
next week we will release 3.0

**Comment by xiaobaitingtao** [comment]
这个问题解决了吗？我使用域名，CF的15年的ssl证书，也试了内网地址，各种方法都试了，依然不行。@Singosgu

**Comment by Singosgu** [comment]
your problem is Nginx skill , not GreaterWMS

**Comment by xiaobaitingtao** [comment]
> 您的问题在于 Nginx 技术，而不是 GreaterWMS

我使用nginx proxy manager，我的反向代理没有问题。我没有使用你的nginx代码。依然报网络错误。

大家架设到公网上，都没有遇到此类问题吗？我架设好几遍。问题依旧。

**Comment by Singosgu** [comment]
那你Nginx代码截图发出来看一下
