### ISSUE TITLE
Data cannot add into Pre pick after order releasing in Outbound.. data add only in Back Order.

### ISSUE THREAD

**Issue by punk02** [GreaterWMS/GreaterWMS#255]
![Screenshot from 2023-01-03 15-00-06](https://user-images.githubusercontent.com/111042260/210331245-84fb9e8d-8a34-4e92-8374-039e716ed450.png)
![Screenshot from 2023-01-03 14-58-54](https://user-images.githubusercontent.com/111042260/210331250-7f0c968b-7c1b-458e-ab83-adb56af71f39.png)
![Screenshot from 2023-01-03 14-58-47](https://user-images.githubusercontent.com/111042260/210331253-856befae-2a29-4cb1-9fbe-5d647781a0c5.png)
![Screenshot from 2023-01-03 14-58-43](https://user-images.githubusercontent.com/111042260/210331257-c0c2e52e-6150-460a-a061-aec2f5ef6cb0.png)

**Comment by Singosgu** [comment]
？what's the problem

**Comment by Singosgu** [comment]
it seems you don't have the on-hand stock
