### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by liliwen365** [GreaterWMS/GreaterWMS#257]
用windows部署后，用Django的runserver可以正常启用项目，但是转用windows自带的IIS服务后，可以进入页面，但是登录时出现网络异常，如下图片
![网络异常](https://user-images.githubusercontent.com/76478019/212232994-d2542a0d-2d79-4544-adc6-d27c33b585a6.png)
；

**Describe the bug**

**Steps to Reproduce**

**Expected behavior**

**Deployment Method**
- [ ] Docker
- [ ] Bare Metal

**Version Information**

**Comment by Singosgu** [comment]
请求地址没有代理，看下请求地址发哪里去了

**Comment by liliwen365** [comment]
我绑定的是3391端口，但是注册请求时是8000端口，如下图
![image](https://user-images.githubusercontent.com/76478019/212589387-8a3f1e99-6a1e-4e2d-87b2-4ec3528dd215.png)

**Comment by Singosgu** [comment]
你看看你端口没改

**Comment by liliwen365** [comment]
不是下面图片地址该吗，改了呀；能不能增加windows的IIS部署教程哈~
![image](https://user-images.githubusercontent.com/76478019/212590320-d9f3c02d-88ac-4302-bff7-4c11d355f443.png)

**Comment by liliwen365** [comment]
这个也改了
![image](https://user-images.githubusercontent.com/76478019/212591899-035e6133-f250-4f7d-8038-0d585ad31854.png)

**Comment by Singosgu** [comment]
quasar build

**Comment by Singosgu** [comment]
然后重启iis

**Comment by liliwen365** [comment]
非常感谢，可以用IIS服务了！
