### ISSUE TITLE
[FR]员工权限怎么设置的？

### ISSUE THREAD

**Issue by yangaphero** [GreaterWMS/GreaterWMS#267]
客户 收货组 经理 发货组 库存管理 主管 供应商  员工权限是怎么分配的？
客户、供应商的权限可以随意修改基本设置、仓库设置，可以查看员工的验证码？
权限只是在vue中进行设置了显示或者关闭？能否对菜单或者是路由进行限制？

**Comment by Singosgu** [comment]
新底层正在测试，新底层会支持任意设置

**Comment by yangaphero** [comment]
什么时候能发出来？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月22日 10:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [GreaterWMS/GreaterWMS] [FR]员工权限怎么设置的？ (Issue #267) |

新底层正在测试，新底层会支持任意设置

**Comment by Singosgu** [comment]
可以关注Bomiot
