### ISSUE TITLE
无法使用daphne起后端asgi

### ISSUE THREAD

**Issue by such-stupid6** [GreaterWMS/GreaterWMS#268]
可以用manage.py runserver 0.0.0.0:8008起后端，可以访问127.0.0.1:8008，用前端也能和数据库交互，但是用daphne起的话，访问127.0.0.1:8008没有任何response，请问是我的daphne版本不对还是其他什么原因呢？

**Comment by Singosgu** [comment]
daphne -p 8008 greaterwms.asgi:application

**Comment by such-stupid6** [comment]
是这么用的没错，但是在本地用curl访问8008，没有任何的response，在停掉daphne之后才会显示Empty reply from server，在浏览器访问8008也看不到回包。我用docker的部署方式倒是能部署，但是我看docker的后端容器里好像也是用manage.py来run server的，有点不太懂是不是我的问题
![image](https://user-images.githubusercontent.com/42930496/222900366-64002160-79eb-4f10-bdb2-1658548e3466.png)
![image](https://user-images.githubusercontent.com/42930496/222900376-0f8c2d69-5e89-4aec-b7cb-989419fd04e8.png)

**Comment by Singosgu** [comment]
8008被占用

**Comment by such-stupid6** [comment]
并没有
![image](https://user-images.githubusercontent.com/42930496/222900494-d3cdace9-3aad-4217-bb0c-1785732101a3.png)
docker我改了8000端口了

**Comment by Singosgu** [comment]
daphne -b 0.0.0.0 -p 8008 greaterwms.asgi:application

**Comment by such-stupid6** [comment]
emmm还是不行
![image](https://user-images.githubusercontent.com/42930496/222900776-b77e4d72-fcda-47be-a464-53d677b9baf2.png)
![image](https://user-images.githubusercontent.com/42930496/222900791-13b60648-111b-4dbc-bfa1-ae7b75ee4e55.png)
![image](https://user-images.githubusercontent.com/42930496/222900802-f2833e38-23a6-4d5f-94ad-dde15e608473.png)
![image](https://user-images.githubusercontent.com/42930496/222900809-45ebe5a7-27ac-4688-a18a-dff05e22c41f.png)

**Comment by Singosgu** [comment]
curl 你的局域网ip，如果是服务器，就curl 公网ip

**Comment by Singosgu** [comment]
你8008换成8009啥的

**Comment by such-stupid6** [comment]
依然不行，我尝试de了一下
![image](https://user-images.githubusercontent.com/42930496/222900959-312ea365-7df4-43d6-a88f-6bd0e71b07b6.png)
![image](https://user-images.githubusercontent.com/42930496/222900996-dc9f6ddf-3191-4bf6-b07f-078575c5b4c9.png)
应该是进入了get_handler了
emm，我也再研究研究吧，学习学习

**Comment by Singosgu** [comment]
这个handler是个统计工具，你可以删除的，应该就好了

**Comment by such-stupid6** [comment]
我给他注释掉了，现在还是连不上，甚至连print也不print了_(:з」∠)_

**Comment by such-stupid6** [comment]
行，原来是
daphne -b 0.0.0.0 -p 8008 greaterwms.asgi:http_application
绷不住了

**Comment by such-stupid6** [comment]
可以小改一下部署文档或者asgi.py了

**Comment by Singosgu** [comment]
可能是daphne库的改变，但是用http_application启动，我们也没有启动过，demo也不是这么弄得，就很奇怪
