### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by panchovilla1970** [GreaterWMS/GreaterWMS#270]
**Problem**
Hi.. I tried to install with Ubuntu 20.04.5 LTS. The problem is that I need to install python 3.9 version since Asgihandler requires minimum this versin. The problem is that I am asked to install attrs package and I cannot install it in the 3.9 version since it is already installed in the python 3.8 version (that comes by default with the Ubuntu). 

So I cannot install the GreaterWMS.

Thank you for your help.

**Comment by Singosgu** [comment]
change your folder

GreaterWMS/greaterwms/asgi.py

to 

https://github.com/GreaterWMS/GreaterWMS/blob/V2.1.17/greaterwms/asgi.py
