### ISSUE TITLE
你好，请问普通用户的权限如何控制呢？我注册了一个普通用户，也能删除一些基本的设置和订单数据[FR]

### ISSUE THREAD

**Issue by FunnyRyan** [GreaterWMS/GreaterWMS#274]
我管理的一个工程项目，最近需要用一套wms来进行材料管理
这个看着挺好

但是好像不太完善

如题，我注册的管理用户和普通用户权限是一样的？

另外，如果大神能接二开，能否给一个联系方式，在这个基础上，不太复杂的，我的需求很简单

**Comment by Singosgu** [comment]
开源版本没有权限控制，不接二开
