### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by Kaliuser24** [GreaterWMS/GreaterWMS#276]
I want to translate the program to a language that is not listed. What settings do I need to change to do this?

**Comment by Singosgu** [comment]
templates/src/i18n

**Comment by Kaliuser24** [comment]
Dev mode.......... spa
 Pkg quasar........ v1.19.4
 Pkg @quasar/app... v2.4.1
 Debugging......... enabled

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
 Configured browser support (at least 88.57% of global marketshare):
 · Chrome for Android >= 103
 · Firefox for Android >= 101
 · Android >= 103
 · Chrome >= 94
 · Edge >= 100
 · Firefox >= 94
 · iOS >= 13.0-13.1
 · Opera >= 85
 · Safari >= 14.1

 App · Reading quasar.conf.js
 App · Checking listening address availability (0.0.0.0:8080)...
 App · Transpiling JS (Babel active)
 App · Extending SPA Webpack config
 App · Generating Webpack entry point
 App · Booting up...

 • Compiling:
 └── SPA █                    0% compiling

  Error: error:0308010C:digital envelope routines::unsupported
  
  - hash:71 new Hash
    node:internal/crypto/hash:71:19
  
  - node:crypto:133 Object.createHash
    node:crypto:133:10
  
  - createHash.js:135 module.exports
    [templates]/[app]/[webpack]/lib/util/createHash.js:135:53
  
  - NormalModule.js:417 NormalModule._initBuildHash
    [templates]/[app]/[webpack]/lib/NormalModule.js:417:16
  
  - NormalModule.js:471 handleParseError
    [templates]/[app]/[webpack]/lib/NormalModule.js:471:10
  
  - NormalModule.js:503 
    [templates]/[app]/[webpack]/lib/NormalModule.js:503:5
  
  - NormalModule.js:358 
    [templates]/[app]/[webpack]/lib/NormalModule.js:358:12
  
  - LoaderRunner.js:373 
    [templates]/[app]/[loader-runner]/lib/LoaderRunner.js:373:3
  
  - LoaderRunner.js:214 iterateNormalLoaders
    [templates]/[app]/[loader-runner]/lib/LoaderRunner.js:214:10
  

 • Compiling:
 └── SPA █████████            40% building 1/4 modules 3 active

/home/kali/Desktop/GreaterWMS-master/templates/node_modules/@quasar/app/node_modules/loader-runner/lib/LoaderRunner.js:133
                if(isError) throw e;
                            ^

[  Error: error:0308010C:digital envelope routines::unsupported
  
  - hash:71 new Hash
    node:internal/crypto/hash:71:19
  
  - node:crypto:133 Object.createHash
    node:crypto:133:10
  
  - createHash.js:135 module.exports
    [templates]/[app]/[webpack]/lib/util/createHash.js:135:53
  
  - NormalModule.js:417 NormalModule._initBuildHash
    [templates]/[app]/[webpack]/lib/NormalModule.js:417:16
  
  - NormalModule.js:471 handleParseError
    [templates]/[app]/[webpack]/lib/NormalModule.js:471:10
  
  - NormalModule.js:503 
    [templates]/[app]/[webpack]/lib/NormalModule.js:503:5
  
  - NormalModule.js:358 
    [templates]/[app]/[webpack]/lib/NormalModule.js:358:12
  
  - LoaderRunner.js:373 
    [templates]/[app]/[loader-runner]/lib/LoaderRunner.js:373:3
  
  - LoaderRunner.js:214 iterateNormalLoaders
    [templates]/[app]/[loader-runner]/lib/LoaderRunner.js:214:10
  
  - LoaderRunner.js:221 iterateNormalLoaders
    [templates]/[app]/[loader-runner]/lib/LoaderRunner.js:221:10
  
] {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
i got this error when i try to launch front end in kali linux

**Comment by Singosgu** [comment]
just node 14.19.3

**Comment by Kaliuser24** [comment]
How can i sign in as user

i cant see any check code

**Comment by Singosgu** [comment]
register an admin

**Comment by Kaliuser24** [comment]
I can sign as a admin but i want to with user

**Comment by Singosgu** [comment]
link
staff site

**Comment by Singosgu** [comment]
you should change you front_web html , use staff_type

or 

you can wait GreaterWMS 3.0
