### ISSUE TITLE
希望有一键安装的docker镜像[FR]

### ISSUE THREAD

**Issue by nathandingx** [GreaterWMS/GreaterWMS#277]
我认为限制这款软件发展的，主要是部署难度

我非常喜欢这款软件，但受限于代码水平，只会在NAS部署简单的docker镜像应用

去年底就有开始自己折腾在NAS上部署，但受限于各种环境问题，迟迟无法上线使用，我想大部分转型期小公司遇到的都是同样的问题，公司不可能专门招程序员去部署环境，软件能否应用完全取决于公司最懂技术的其他部门人员

我个人是支持商业化的，但软件如果不能像odoo的docker镜像一样可以简单的部署免费社区版本（虽然也稍微复杂，但能解决环境问题，所有人按教程走都能部署成功），让用户感受到它的强大，又如何引流到付费的商业版本呢？

**Comment by Singosgu** [comment]
不是有docker-compose在软件里面吗？直接docker就可以了

**Comment by nathandingx** [comment]
确实是用过，但docker搭建的总是有毛病。例如下载了表单，填好后无法上传；数据也无法重置之类的问题，比较头疼

**Comment by Singosgu** [comment]
可能版本不对吧，去dockerhub看下最新版本，docker我们没有怎么编辑
