### ISSUE TITLE
API documents and instructions

### ISSUE THREAD

**Issue by wswapneel** [GreaterWMS/GreaterWMS#281]
Hi,

I am so thankful for GreatWMS, a very good project. I deployed the development server yesterday but can't find the API documents and instructions to create and connect to another order management and courier services like FedEx, UPS... I would like to know if you have the same kind of set of instructions to create API's as for deployment of the server. Your help is greatly appreciated, Thank you ! Neel

**Comment by Singosgu** [comment]
you can use drf-yasg to setup the api docs

**Comment by wswapneel** [comment]
Hi Singosgu, I am not too familiar with this, can you please send me step by step instructions on how to do it?
Thank you! Neel
