### ISSUE TITLE
[BUG] Issues during the installation process

### ISSUE THREAD

**Issue by ibrahimdefinta** [GreaterWMS/GreaterWMS#307]
**Hi** @Singosgu, 

First of all, I would like to express my gratitude for this impressive system.
However, when I was running the installation process, following the guide you provided, I encountered a problem at the "Create Database" step - python manage.py makemigrations with the following issue:
in 'module'
from pandas.core.util.hashing import ( # noqa:F401
ValueError: source code string cannot contain null bytes.

I would appreciate your assistance and any insights on how to fix it.
Thank you.

![image](https://github.com/GreaterWMS/GreaterWMS/assets/75490998/c8b37f6e-d160-4e32-90a6-9d5d0ded4130)

**Comment by Singosgu** [comment]
please use windows cmd . 
don't use powershell

**Comment by ibrahimdefinta** [comment]
Hi @Singosgu,

I have already used Windows Command Prompt, but the same error still appears, which is: "ValueError: source code string cannot contain null bytes" along with the capture.

Please help me.
Thank you.

![image](https://github.com/GreaterWMS/GreaterWMS/assets/75490998/61875ac3-defa-4d7c-b2dd-3dc073ff9b99)

**Comment by Singosgu** [comment]
I think you use xlrd already，you should use xlrd verson less than 2.0.0

**Comment by ibrahimdefinta** [comment]
I have already used xlrd version less than 2.0.0, specifically version 1.2.0, and have reinstalled it. However, I still encounter the same error. 

![image](https://github.com/GreaterWMS/GreaterWMS/assets/75490998/2ab797a2-e43b-4b1d-848a-df6bbe631864)

**Comment by Singosgu** [comment]
I check this issue from Pandas , it shows you install xlrd

I think you should use env to install requirements.txt
