### ISSUE TITLE
请问下前端有丰富一点的表单界面吗

### ISSUE THREAD

**Issue by skyydq** [GreaterWMS/GreaterWMS#32]
请问下前端有丰富一点的表单界面吗, 目前这表单界面 都是一列

**Comment by Singosgu** [comment]
举个例子

**Comment by skyydq** [comment]
比如新增 单据
![image](https://user-images.githubusercontent.com/17490986/122562871-0faf7a80-d033-11eb-8470-f130bec604a0.png)

**Comment by skyydq** [comment]
整体界面 都是高大上不错，但是新增表单 界面都是一列显示，很单调

**Comment by Singosgu** [comment]
嗯，对的，现在只有在做整体页面功能全部实现，你所说的页面优化，都是会在未来实现
