### ISSUE TITLE
[question]docker部署出现问题

### ISSUE THREAD

**Issue by smilecat2788** [GreaterWMS/GreaterWMS#329]
root@ubuntu:/home/GreaterWMS# docker-compose up -d
[+] Running 2/3
 ? Network greaterwms_basic      Created                                                                                                                                              0.2s
 ? Container greaterwms_backend  Started                                                                                                                                              1.0s
 ? Container greaterwms_front    Starting                                                                                                                                             2.1s
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/GreaterWMS/templates/web_start.sh": permission denied: unknown

环境为ubuntu server 22.04
后端可以正常启动，但是前端启动失败

**Comment by Singosgu** [comment]
提权

**Comment by smilecat2788** [comment]
现在docker正常启动了但是
![image](https://github.com/GreaterWMS/GreaterWMS/assets/109615952/48252837-bb48-46eb-8b4f-c20d284c0293)
无法登录
![image](https://github.com/GreaterWMS/GreaterWMS/assets/109615952/091d3e07-648a-4908-ac41-ea5c18929389)
baseurl也修改成http://127.0.0.1:8282

**Comment by smilecat2788** [comment]
后端日志
Welcome To GreaterWMS
No changes detected
Welcome To GreaterWMS
Operations to perform:
  Apply all migrations: admin, asn, auth, binproperty, binset, binsize, capital, company, contenttypes, customer, cyclecount, dn, driver, goods, goodsbrand, goodsclass, goodscolor, goodsorigin, goodsshape, goodsspecs, goodsunit, payment, scanner, sessions, staff, stock, supplier, throttle, userprofile, warehouse
Running migrations:
  No migrations to apply.
2023-08-09 02:59:53,352 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-08-09 02:59:53,353 WARN No file matches via include "/etc/supervisor/conf.d/*.conf"
2023-08-09 02:59:53,353 WARN For [program:greaterwms], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
Unlinking stale socket /var/run/supervisor.sock
2023-08-09 02:59:53,670 INFO RPC interface 'supervisor' initialized
2023-08-09 02:59:53,671 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-08-09 02:59:53,672 INFO supervisord started with pid 18
2023-08-09 02:59:54,676 INFO spawned: 'greaterwms' with pid 20
2023-08-09 02:59:55,678 INFO success: greaterwms entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Welcome To GreaterWMS
No changes detected
Welcome To GreaterWMS
Operations to perform:
  Apply all migrations: admin, asn, auth, binproperty, binset, binsize, capital, company, contenttypes, customer, cyclecount, dn, driver, goods, goodsbrand, goodsclass, goodscolor, goodsorigin, goodsshape, goodsspecs, goodsunit, payment, scanner, sessions, staff, stock, supplier, throttle, userprofile, warehouse
Running migrations:
  No migrations to apply.
2023-08-09 03:34:19,736 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-08-09 03:34:19,737 WARN No file matches via include "/etc/supervisor/conf.d/*.conf"
2023-08-09 03:34:19,737 WARN For [program:greaterwms], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
Unlinking stale socket /var/run/supervisor.sock
2023-08-09 03:34:20,054 INFO RPC interface 'supervisor' initialized
2023-08-09 03:34:20,055 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-08-09 03:34:20,056 INFO supervisord started with pid 17
2023-08-09 03:34:21,059 INFO spawned: 'greaterwms' with pid 19
2023-08-09 03:34:22,063 INFO success: greaterwms entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
前端日志
Build succeeded

 Build mode........ spa
 Pkg quasar........ v1.19.4
 Pkg @quasar/app... v2.4.1
 Debugging......... no
 Publishing........ no
 Transpiled JS..... yes (Babel)
 ==================
 Output folder..... /GreaterWMS/templates/dist/spa

 Tip: Built files are meant to be served over an HTTP server
      Opening index.html over file:// won't work

 Tip: You can use "$ quasar serve" command to create a web server,
      both for testing or production. Type "$ quasar serve -h" for
      parameters. Also, an npm script (usually named "start") can
      be added for deployment environments.
      If you're using Vue Router "history" mode, don't forget to
      specify the "--history" parameter: "$ quasar serve --history"


 Dev mode.......... spa
 Pkg quasar........ v1.19.4
 Pkg @quasar/app... v2.4.1
 Debugging......... enabled

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
 Configured browser support (at least 88.57% of global marketshare):
 · Chrome for Android >= 103
 · Firefox for Android >= 101
 · Android >= 103
 · Chrome >= 94
 · Edge >= 100
 · Firefox >= 94
 · iOS >= 13.0-13.1
 · Opera >= 85
 · Safari >= 14.1

 App · Reading quasar.conf.js
 App · Checking listening address availability (0.0.0.0:8080)...
 App · Transpiling JS (Babel active)
 App · Extending SPA Webpack config
 App · Generating Webpack entry point
 App · Booting up...
 App · Compiling SPA...
 App · Compiled SPA done in 86064 ms
 DONE  Compiled successfully in 86082ms3:37:25 AM


 N  App dir........... /GreaterWMS/templates
    App URL........... http://localhost:8080
    Dev mode.......... spa
    Pkg quasar........ v1.19.4
    Pkg @quasar/app... v2.4.1
    Transpiled JS..... yes (Babel)
  
[34mℹ[39m [90m｢wds｣[39m: Project is running at http://0.0.0.0:8080/
[34mℹ[39m [90m｢wds｣[39m: webpack output is served from

**Comment by Singosgu** [comment]
好像你没有build成功

**Comment by smilecat2788** [comment]
那我应该如何做呢，我按照docker部署教程部署了两遍还是这样

**Comment by Singosgu** [comment]
chmod +x web_start.sh

**Comment by smilecat2788** [comment]
![image](https://github.com/GreaterWMS/GreaterWMS/assets/109615952/2343f083-6746-4690-a95c-9c4e55ad4952)
这样应该是bulid成功了吧，但是还是会报网络异常，是不是前后端没连接起来
![image](https://github.com/GreaterWMS/GreaterWMS/assets/109615952/e7cf4f70-ada6-4890-9f92-cf0d9799d8a5)

**Comment by Singosgu** [comment]
baseurl自己调整一下

**Comment by smilecat2788** [comment]
当我使用反向代理时网页报错如下
![image](https://github.com/GreaterWMS/GreaterWMS/assets/109615952/51d1bdcf-f48d-42e5-8ab9-3d3cb5fa676b)
不使用反向代理时网页报错如下
![image](https://github.com/GreaterWMS/GreaterWMS/assets/109615952/381bab9f-e9d7-432b-aa8a-acde4cc6b2dc)
看报错好像已经定向到后端192.168.1.50:8282了，我尝试了直接在服务器运行后端和容器里运行后端，都没法连接到
顺便一提好像帮助文档的网站没了
![image](https://github.com/GreaterWMS/GreaterWMS/assets/109615952/13dffc2e-20de-484d-953d-f34bd1220c31)

**Comment by Singosgu** [comment]
在更换服务器，明天可以访问，你这个好像是nginx的问题，配置的nginx发一下

**Comment by smilecat2788** [comment]
我今天回家试了一下，直接走局域网访问可以打开，当我使用公网http访问时会出现网络错误，没有经过nginx，这是我完整的做法，希望能帮助你定位问题

1. 从GitHub克隆仓库到本地
2. 提权web_start.sh和backend_start.sh
3. 修改compose文件的端口，前端8281:8080，后端8282:8000，修改baseurl.txt地址为http:192.168.1.50:8282
4. 执行docker-compose up -d
5. 访问公网IP:8181

**Comment by Singosgu** [comment]
修改之后，需要quasar build一下

**Comment by Singosgu** [comment]
你该不会是群晖的nas吧

**Comment by finalxcode** [comment]
@Singosgu  Is this project controlled by permissions specific to different roles?

**Comment by Singosgu** [comment]
Edit by yourself , use staff_type
