### ISSUE TITLE
[FR] An additional Step for holding before product goes to the inventory

### ISSUE THREAD

**Issue by piyushitc** [GreaterWMS/GreaterWMS#333]
**Problem**
I am trying to get to your hosted server of 56yhz and it won't reach to it. 

**Suggested solution**
It should reach the domain but I guess the server can't be reached.

**Do you want to develop this?**
I am trying to include a step where after inbound has been completed, product shows into a pending stage and upon confirmation it shows up in the inventory.

**Comment by Singosgu** [comment]
we update 56yhz yesterday . it's ok now 

if you want to pending stage , you can edit asn/sorted url

**Comment by piyushitc** [comment]
So we can change the sorted URL as pending and upon confirmation it will go to the inventory ? Great Idea, Thanks a lot.

**Comment by Singosgu** [comment]
No, you can set 1 bin location , bin type is not Normal , move the goods to this bin after you receive all goods , just Normal bin type will be the can order stock
