### ISSUE TITLE
[BUG] Windows installation bug

### ISSUE THREAD

**Issue by piyushitc** [GreaterWMS/GreaterWMS#334]
**Describe the bug**

App is running fine locally but when i am trying to deploy it to my IP using quasar build it's giving me this error. 
OS: Windows

Compiling:
 └── SPA ███████████████████  93% after chunk asset optimization

  Error: error:0308010C:digital envelope routines::unsupported

  - hash:69 new Hash
    node:internal/crypto/hash:69:19

  - node:crypto:133 Object.createHash
    node:crypto:133:10

  - index.js:228 CompressionPlugin.getTask
    [templates]/[app]/[compression-webpack-plugin]/dist/index.js:228:38

  - getTask.next

  - index.js:274
    [templates]/[app]/[compression-webpack-plugin]/dist/index.js:274:59

  - index.js:298 CompressionPlugin.runTasks
    [templates]/[app]/[compression-webpack-plugin]/dist/index.js:298:9

  - index.js:321 compressionFn
    [templates]/[app]/[compression-webpack-plugin]/dist/index.js:321:18

  - index.js:333
    [templates]/[app]/[compression-webpack-plugin]/dist/index.js:333:7

  - task_queues:95 process.processTicksAndRejections
    node:internal/process/task_queues:95:5

**Steps to Reproduce**

1.Follow everything given as windows installation module.

**Expected behavior**

**Deployment Method**
- [ ] Windows

**Version Information**

**Comment by Singosgu** [comment]
RAM + ROM is not enough
