### ISSUE TITLE
[FR] Integrate MYSQL DATABASE 

### ISSUE THREAD

**Issue by stockarea** [GreaterWMS/GreaterWMS#340]
**Is your feature request the result of a bug?**
Please link it here.

**Problem**
A clear and concise description of what the problem is. e.g. I'm always frustrated when [...]

Right now, the database resides with sqlite and its very limiting. By when can we have MYSQL OR POSTGRESQL

**Suggested solution**

**Describe alternatives you've considered**

**Examples of other systems**
Show how other software handles your FR if you have examples.

**Do you want to develop this?**
If so please describe briefly how you would like to implement it (so we can give advice) and if you have experience in the needed technology (you do not need to be a pro - this is just as a information for us).

**Comment by Singosgu** [comment]
pip install mysqlclient

**Comment by Avey777** [comment]
> pip install mysqlclient

How to use MySQL
