### ISSUE TITLE
admin/admin User Name Or Password Error

### ISSUE THREAD

**Issue by githubmyname** [GreaterWMS/GreaterWMS#341]
UserNameOrPassword Error
![截图_选择区域_20231107144241](https://github.com/GreaterWMS/GreaterWMS/assets/149666360/d5c22685-d1a0-41e7-8b34-ffde538a4dfe)

**Comment by Singosgu** [comment]
Chinese GOV close my server

**Comment by githubmyname** [comment]
> Chinese GOV close my server

https://github.com/GreaterWMS/GreaterWMS/releases/download/V2.1.47/GreaterWMS-win-2.1.47.zip

I'm using Lan Version Download .
Doesn't he support local server running? Do I have to connect to your server?

**Comment by Singosgu** [comment]
Yup, but you must get the lan ip from our server to auto-registe one admin user
it is be closed by chinese gov

**Comment by githubmyname** [comment]
The backend isn't fully open source? Can't use it offline?

> Yup, but you must get the lan ip from our server to auto-registe one admin user it is be closed by chinese gov

**Comment by Singosgu** [comment]
fully open source . Lan version just want to give somebody who don't have IT team to use .
