### ISSUE TITLE
[BUG] Run failed

### ISSUE THREAD

**Issue by Jengro777** [GreaterWMS/GreaterWMS#342]
![image](https://github.com/GreaterWMS/GreaterWMS/assets/35259040/8a87d997-5cd3-483f-b0e6-56d5561504a6)

**Comment by huok** [comment]
I met the same bug.

**Comment by Singosgu** [comment]
check your baseurl

**Comment by Avey777** [comment]
defaut:  http://127.0.0.1:8008  is not good

change1 : http://10.243.0.7:8008  is not good

change2 : http://10.243.0.7:8080  is not goo

**Comment by Avey777** [comment]
That's ok. It's a firewall problem.

**Comment by Singosgu** [comment]
ok

**Comment by huok** [comment]
how did you fix this problem? howto set firewall?

**Comment by Avey777** [comment]
> how did you fix this problem? howto set firewall?

The IP address you requested and the IP address set by baseurl should be set to one, I think you should be experiencing this problem
