### ISSUE TITLE
运行后是空白页

### ISSUE THREAD

**Issue by huok** [GreaterWMS/GreaterWMS#343]
运行daphne -b 0.0.0.0 -p 8008 greaterwms.asgi:application后，用浏览器访问，是空白页

**Comment by Singosgu** [comment]
quasar build前端一下

**Comment by huok** [comment]
已执行，访问得到的index.html的源码如下图，显示还是空白页
![image](https://github.com/GreaterWMS/GreaterWMS/assets/29275923/690312ed-ba96-470f-b599-c386e3260715)

**Comment by Singosgu** [comment]
你这就是未执行
