### ISSUE TITLE
我用你的邮箱elvis.shi@56yhz.com联系你，被退信了。

### ISSUE THREAD

**Issue by huok** [GreaterWMS/GreaterWMS#344]
我有一些合作事项，想联系你。结果被退信了。
我有gmail 和 qqmail 都尝试了，结果都是一样的。
希望能有你的其他联系方式。

我的 gmail是 huok1980@gmail.com

**Comment by Singosgu** [comment]
最近官网调整，邮箱转服务运营商，暂时不可用
