### ISSUE TITLE
adding more warehouse & company? 

### ISSUE THREAD

**Issue by wangweitung** [GreaterWMS/GreaterWMS#345]
**Is your feature request the result of a bug?**
no

**Problem**
I can not create 2 warehouse or company

![图片](https://github.com/GreaterWMS/GreaterWMS/assets/8080125/1a5db967-a614-4b46-8f50-b3101dda25f1)

**Suggested solution**
Let user creat more warehouse or company

**Describe alternatives you've considered**
1 company often have muti warehouses

**Examples of other systems**
no ...

**Do you want to develop this?**
just a user.

**Comment by Singosgu** [comment]
register 1 more admin，you will get more warehouse

**Comment by wangweitung** [comment]
> register 1 more admin，you will get more warehouse

thx，will try later.

another problem:

open with firefox showing not properly like below:

![图片](https://github.com/GreaterWMS/GreaterWMS/assets/8080125/1c855b04-f20c-41a1-ae75-e7eef70dade6)

**Comment by Singosgu** [comment]
it seems firefox not support well

**Comment by wangweitung** [comment]
> register 1 more admin，you will get more warehouse

admin A  , warehouse 1
admin B ，warehouse 2

if  A wants  to use warehouse 2，  do  I have to register a user under admin B？

**Comment by Singosgu** [comment]
No， choose your warehouse ,and login 

if you login by admin B , it will auto change to warehouse 2

**Comment by wangweitung** [comment]
> No， choose your warehouse ,and login
> 
> if you login by admin B , it will auto change to warehouse 2

Still confused for muti admins.

How could I list all the admins and delete one of them ?

**Comment by Singosgu** [comment]
why you want to delete admin?

**Comment by wangweitung** [comment]
> why you want to delete admin?

I create some test admin user, after test , I want to clear the data , and begin to use

**Comment by Singosgu** [comment]
one admin is just one database , If you want to use by only one admin , delete the other warehouse is ok for u

**Comment by wangweitung** [comment]
> one admin is just one database , If you want to use by only one admin , delete the other warehouse is ok for u

Thx
