### ISSUE TITLE
[BUG] Server Error(500)

### ISSUE THREAD

**Issue by killlowkey** [GreaterWMS/GreaterWMS#352]
When using an ipv6 address to access the wms system, a Server Error 500 error will occur. Looking at the cause of the system error, the troubleshooting is that the ip field in the throttle table is too short, resulting in records that cannot be inserted. The length of the ip field needs to be increased.

https://github.com/GreaterWMS/GreaterWMS/blob/d0dc20ecf587f5575a86341f2cc81c4517b785af/throttle/models.py#L3-L15

![image](https://github.com/GreaterWMS/GreaterWMS/assets/41176828/46a08cbd-5495-4af5-8592-7a7780dca17b)

After manually adjusting the IP field length to 255, the system runs normally.
![image](https://github.com/GreaterWMS/GreaterWMS/assets/41176828/cc78c52e-fd25-449a-a934-5d8e318f624e)

**Comment by Singosgu** [comment]
ok , tks , we will fix it
