### ISSUE TITLE
[BUG] Network Exception

### ISSUE THREAD

**Issue by spalex78** [GreaterWMS/GreaterWMS#360]
Network exception that prohibits admin registration or login.

![greaterwms](https://github.com/GreaterWMS/GreaterWMS/assets/87479780/5a848cc2-a9e2-4639-97f0-eba530b6d6a3)

**Comment by spalex78** [comment]
Just found out that it happens only on the latest Chrome

**Comment by Singosgu** [comment]
change your baseurl in templates

**Comment by spalex78** [comment]
baseurl is correct and everything works correctly on Edge and Firefox

**Comment by Singosgu** [comment]
delete cookie and localstorage

**Comment by kd992102** [comment]
Does this bug fixed?

**Comment by Singosgu** [comment]
No one told u , it is a bug

**Comment by simple51** [comment]
Modify the baseurl file and ctrl+F5
