### ISSUE TITLE
Demo link is not working.[BUG]

### ISSUE THREAD

**Issue by 18gaurav2021** [GreaterWMS/GreaterWMS#364]
**Describe the bug**

**Steps to Reproduce**

**Expected behavior**

**Deployment Method**
- [ ] Docker
- [ ] Bare Metal

**Version Information**

**Comment by Singosgu** [comment]
yes，we close it

**Comment by 18gaurav2021** [comment]
Hi,
kindly update and let me know when it starts working again.
Also you mention to change the baseurl + '/Docs/' but it is not existing in
code base.

**Comment by Singosgu** [comment]
api/docs/

**Comment by 18gaurav2021** [comment]
Is it a folder 📂? Not visible in the code base.

**Comment by Singosgu** [comment]
in greaterwms/urls.py

urlpatterns += [
    path('api/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/debug/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/docs/', SpectacularRedocView.as_view(url_name='schema'), name='docs'),
]

you can find the api link

**Comment by 18gaurav2021** [comment]
Hi,
I have following questions:
1. While register , i am not able to register, it is showing network error.
2. What i have to do to make it proper functional on my local system.
Kindly guide in detail.I appreciate your help.

**Comment by Singosgu** [comment]
Change your baseurl and then quasar build

after that restart daphne to start back end again
