### ISSUE TITLE
[BUG] Enter bug description

### ISSUE THREAD

**Issue by Mo-esmail** [GreaterWMS/GreaterWMS#367]
**Describe the bug**
Logging in as a staff member isn't working.
if i try to log in as a staff member i still get same permissions as admin. for example if i log in as a supplier i still can see all staff members and even delete and create staff members
**Steps to Reproduce**

1.log in with any other staff member credentials 
2. go to staff members and try to modify it

**Expected behavior**
if i log in with a specific role i only get permission to do things permitted for this role 

**Deployment Method**
Docker

**Version Information**

**Comment by Singosgu** [comment]
use staff_type to edit by yourself
