### ISSUE TITLE
[BUG] 你好，我在centos使用docker 部署成功了，但是接口报错network exception

### ISSUE THREAD

**Issue by mc0716** [GreaterWMS/GreaterWMS#371]
是我哪里没有配置好吗？

![image](https://github.com/GreaterWMS/GreaterWMS/assets/29155327/39034ebf-7e66-4b31-9a88-d526306887f5)
![image](https://github.com/GreaterWMS/GreaterWMS/assets/29155327/2bb1b735-3b1d-411a-8e1a-0948175333a9)
![Uploading image.png…]()

**Comment by Singosgu** [comment]
改baseurl

**Comment by mc0716** [comment]
> 改baseurl
`GreaterWMS/templates/public/statics/` 路径下有个 `baseurl.txt` 我复制了一份改名成 `baseurl.js`并把里面的url改成了服务器ip，但是`quasar build` 构建的时候就会报错，如下图
![image](https://github.com/GreaterWMS/GreaterWMS/assets/29155327/bcffbffc-634e-46b3-aaa9-263798207a27)

![image](https://github.com/GreaterWMS/GreaterWMS/assets/29155327/b2e9ceee-559f-4298-bf15-9052006c09f0)

**Comment by Singosgu** [comment]
看教程

**Comment by mc0716** [comment]
> 看教程
已解决，教程那里有误导
命令`vim templates/public/statics/baseurl.js`我以为要把`baseurl.txt`修改成`baseurl.js`呢，命令应该是`vim templates/public/statics/baseurl.txt`建议修改一下教程
![image](https://github.com/GreaterWMS/GreaterWMS/assets/29155327/79f44552-889d-4d68-9263-f812d81a746b)

**Comment by Singosgu** [comment]
是教程太老了，现在要出新版，所以就不修改了
