### ISSUE TITLE
docker-compose up 的时候，pull access denied for cow11023

### ISSUE THREAD

**Issue by wangjiahong** [GreaterWMS/GreaterWMS#69]
非常棒的项目 感谢
![image](https://user-images.githubusercontent.com/14320144/131254895-3a91046e-77a0-4c40-9176-73a6d556d2a7.png)
感谢分享 谢谢

**Comment by Singosgu** [comment]
正在测试，还没有发布

**Comment by cow11023** [comment]
是用的国内镜像那个images么mysql 是哪里来的。。。docker-compose.yml里没加mysql
