### ISSUE TITLE
你好 请问相同sku放在同一个库位，库存记录为什么不是数量累加合并一条记录 而是多条记录？

### ISSUE THREAD

**Issue by xiaoqiaotq** [GreaterWMS/GreaterWMS#89]
![wmsa](https://user-images.githubusercontent.com/8088060/132806314-a3933fac-dc2f-4fe7-8b78-91e38ec2fc90.png)

**Comment by Singosgu** [comment]
因为先进先出啊

**Comment by xiaoqiaotq** [comment]
是通过修改时间判断先后，这个有批次的概念吗？

**Comment by Singosgu** [comment]
是存储唯一码加时间来判断的
